In [135]:
import pandas as pd
df=pd.read_csv('requestedDataFormatted(1).csv',sep=';',encoding='latin-1')
df['anio']=df['Start date'].apply(lambda x: int(x.split('/')[2]))
train=df[(df['anio']==2014) | (df['anio']==2015)|(df['anio']==2016)|(df['anio']==2013)|(df['anio']==2012)|(df['anio']==2011)|(df['anio']==2010)]
xtrain=train.iloc[:,[7,9,10]].values
ytrain=train.iloc[:,[8]].values

xtest1=df[df['anio']==2017].iloc[:,[7,9,10]].values
ytest1=df[df['anio']==2017].iloc[:,[8]].values

xtest2=df[df['anio']==2018].iloc[:,[7,9,10]].values
ytest2=df[df['anio']==2018].iloc[:,[8]].values

xtest3=df[df['anio']==2019].iloc[:,[7,9,10]].values
ytest3=df[df['anio']==2019].iloc[:,[8]].values

In [136]:
import math 
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np
# difference of lasso and ridge regression is that some of the coefficients can be zero i.e. some of the features are 
# completely neglected
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [137]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
xtrain =scaler.fit_transform(xtrain)
scaler=StandardScaler()
xtest1=scaler.fit_transform(xtest1)
scaler=StandardScaler()
xtest2=scaler.fit_transform(xtest2)
scaler=StandardScaler()
xtest3=scaler.fit_transform(xtest3)

In [149]:
lasso = Lasso()
lasso.fit(xtrain,ytrain)
train_score=lasso.score(xtrain,ytrain)
test_score=lasso.score(xtest2,ytest2)
coeff_used = np.sum(lasso.coef_!=0)

In [150]:
print ("training score:", train_score) 
print ("test score: ", test_score)
print ("number of features used: ", coeff_used)

training score: 0.6485308461905317
test score:  -190.14290907661476
number of features used:  3

In [140]:
lasso001 = Lasso(alpha=0.0000001, max_iter=10e5)
lasso001.fit(xtrain,ytrain)
train_score001=lasso001.score(xtrain,ytrain)
test_score001=lasso001.score(xtest1,ytest1)
coeff_used001 = np.sum(lasso001.coef_!=0)
print ("training score for alpha=0.01:", train_score001) 
print ("test score for alpha =0.01: ", test_score001)
print ("number of features used: for alpha =0.01:", coeff_used001)

training score for alpha=0.01: 0.6485308462035039
test score for alpha =0.01:  0.6722749661471636
number of features used: for alpha =0.01: 3

In [152]:
lasso.predict(xtest2)

array([-17089.93257597, 138662.87267897,  29635.90900051, 137670.11629716,
        48933.79340606, 259258.76738835,  30724.31560308,   1211.02204148,
         9594.47270156, 450628.28946774, 124255.73819289, -31029.80864629])

In [153]:
df[df['anio']==2018].Country

124                              Paraguay
125                             Argentina
126                             Argentina
127      Bolivia (Plurinational State of)
128                                Brazil
129                              Colombia
130                                Brazil
131    Venezuela (Bolivarian Republic of)
132    Venezuela (Bolivarian Republic of)
133                              Colombia
134                              Paraguay
135                             Argentina
Name: Country, dtype: object

In [154]:
df

,Start date,End date,Country,ISO,Location,Disaster type,Disaster subtype,Total affected,Total damage ('000 US$),Insured losses ('000 US$),Total deaths,Disaster No.,anio
0,1/1/2010,13/1/2010,Bolivia,BOL,"Beni, Chuquisaca, Cochabamba, La Paz and Santa...",Flood,Riverine flood,227860,0,0,26,2010-0023,2010
1,9/1/2010,1/2/2010,Ecuador,ECU,"Cotopaxi, El Oro, Esmeraldas, Guayas provinces",Flood,Riverine flood,500,0,0,12,2010-0056,2010
2,10/2/2010,17/2/2010,Peru,PER,"La Esperanza, El Porvenir, Salaverry towns (Tr...",Flood,Riverine flood,80000,0,0,20,2010-0065,2010
3,4/4/2010,12/4/2010,Brazil,BRA,"Niteroi, Sao Goncalo, Rio de Janeiro districts...",Flood,Riverine flood,74938,200000,0,256,2010-0147,2010
4,6/4/2010,7/3/2011,Colombia,COL,"Sucre, Bolivar, Cordoba, Antioquia, Atlantico,...",Flood,Riverine flood,2791999,1000000,14000,418,2010-0168,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,8/4/2019,9/4/2019,Brazil,BRA,"Rio de Janeiro, Maranhao, Piaui, Sao Paulo states",Flood,--,4500,0,0,10,2019-0146,2019
149,23/4/2019,23/4/2019,Argentina,ARG,"Resistencia, Barranqueras, General Pinedo, Cha...",Flood,--,1800,0,0,2,2019-0185,2019
150,8/5/2019,9/5/2019,Paraguay,PRY,"Asuncion, Pilar",Flood,Riverine flood,310595,0,0,0,2019-0245,2019
151,11/6/2019,24/6/2019,Uruguay,URY,"Florida, Durazno",Flood,--,7406,0,0,0,2019-0273,2019
152,13/6/2019,13/6/2019,Brazil,BRA,Pernambuco state,Flood,Flash flood,30000,0,0,7,2019-0309,2019